### ISSUE TITLE
Add license informations (Apache-2.0)

### ISSUE THREAD

**Issue by ST3tter** [oxon/ardublockly#20]
To add the license informations we have to:

- [ ] Include the existing copyrights
- [ ] Including the full text of license in modified software.
- [ ] Stating significant changes made to software.
- [ ] If the library has a "NOTICE" file we have to include that as well
- [ ] Create a static page on the OXOcard homepage with all this informations and links

more informations about the Apache License 2.0 (Apache-2.0) [here](https://tldrlegal.com/license/apache-license-2.0-(apache-2.0))

**Comment by tynx** [comment]
Currently used AND adapted projects/SW:
- blockly
- ardublockly
- serial-port-json-server
- arduino-create-agent

Currently (only and directly) used projects/SW:
- wordpress
- create-dmg
- docker
- avrdude
- arduino

I know we're still missing some....

**Comment by tynx** [comment]
@ST3tter This is done now, right?

**Comment by ST3tter** [comment]
Yes it's done
