### ISSUE TITLE
Missing blocks for the OXOcard

### ISSUE THREAD

**Issue by ST3tter** [oxon/ardublockly#4]
The following blocks are not implemeted yet:

- [x] drawRectangle(x, y, w, h, brightness)
- [x] drawFilledRectangle(x, y, w, h, brightness)
- [x] drawCircle(x, y, r, brightness)
- [x] drawFilledCircle(x, y, r, brightness)
- [x] drawTriangle(x0, y0, x1, y1, x2, y2, brightness)
- [x] drawFilledTriangle(x0, y0, x1, y1, x2, y2, brightness)
- [x] drawChar(x, y, c, brightness)
- [x] drawDigit(x, y, digit, brightness)
- [x] drawNumber(x, y, digit, brightness)
- [x] random(int)

**Comment by tynx** [comment]
- [x] getOrientation
- [x] isAccelerationUp
- [x] isAccelerationDown
- [x] isAccelerationRight
- [x] isAccelerationLeft
- [x] getXAcceleration
- [x] getYAcceleration
- [x] getZAcceleration

They currently produced wrong code.

![invalid_code_output](https://user-images.githubusercontent.com/1826652/28019566-ae1699cc-6581-11e7-8712-4278a74905e4.png)

**Comment by ST3tter** [comment]
- [x] Is button pressed
- [x] Get timer seconds

Are wrong too
